#\!/bin/bash
# Airレジ自動化のcron設定スクリプト

echo "🕐 Airレジ自動化のcron設定"
echo "========================="
echo ""
echo "以下のcron設定を追加することで、定期的に売上データを取得・通知します："
echo ""
echo "1. 毎時0分に実行（営業時間中）"
echo "   0 10-18 * * * /usr/local/bin/node airregi-full-automation.js > /tmp/airregi-cron.log 2>&1"
echo ""
echo "2. 特定時刻に詳細レポート（11時、15時、19時）"
echo "   0 11,15,19 * * * cd /Users/apple/Projects/mothership/vision-engine && /usr/local/bin/node airregi-full-automation.js > /tmp/airregi-cron.log 2>&1"
echo ""
echo "3. 営業終了後の日次サマリー（19時）"
echo "   0 19 * * * cd /Users/apple/Projects/mothership/vision-engine && /usr/local/bin/node airregi-full-automation.js > /tmp/airregi-cron.log 2>&1"
echo ""
echo "設定方法："
echo "1. ターミナルで以下を実行："
echo "   crontab -e"
echo ""
echo "2. 上記のcron設定をコピーして貼り付け"
echo ""
echo "3. 保存して終了（vim の場合: :wq）"
echo ""
echo "現在のcron設定を確認："
echo "   crontab -l"
echo ""
echo "========================="
echo ""

# 現在のcron設定を表示
echo "📋 現在のcron設定:"
crontab -l 2>/dev/null || echo "（設定なし）"
EOF < /dev/null