#!/bin/bash
# 営業時間に合わせたcron設定更新スクリプト

echo "⏰ 営業時間に合わせたcron設定"
echo "==============================="
echo ""
echo "現在の設定:"
crontab -l | grep airregi
echo ""
echo "新しい推奨設定:"
echo ""
echo "# Airレジ売上データ自動取得（30分ごと）"
echo "# 月～金: 8:00-23:30"
echo "0,30 8-23 * * 1-5 cd /Users/apple/Projects/mothership/vision-engine && /usr/local/bin/node airregi-full-automation.js > /tmp/airregi-cron.log 2>&1"
echo ""
echo "# 土曜日: 10:30-23:30" 
echo "30 10-23 * * 6 cd /Users/apple/Projects/mothership/vision-engine && /usr/local/bin/node airregi-full-automation.js > /tmp/airregi-cron.log 2>&1"
echo "0 11-23 * * 6 cd /Users/apple/Projects/mothership/vision-engine && /usr/local/bin/node airregi-full-automation.js > /tmp/airregi-cron.log 2>&1"
echo ""
echo "# 日曜日・祝日: 10:30-23:00"
echo "30 10-22 * * 0 cd /Users/apple/Projects/mothership/vision-engine && /usr/local/bin/node airregi-full-automation.js > /tmp/airregi-cron.log 2>&1"
echo "0 11-22 * * 0 cd /Users/apple/Projects/mothership/vision-engine && /usr/local/bin/node airregi-full-automation.js > /tmp/airregi-cron.log 2>&1"
echo ""
echo "==============================="
echo ""
echo "更新方法:"
echo "1. crontab -e"
echo "2. 既存のairregi関連の設定を削除"
echo "3. 上記の新しい設定を追加"
echo "4. 保存して終了"