#!/bin/bash
echo "🚀 GitHub自動セットアップを開始します"
echo ""
echo "このスクリプトは対話的な入力が必要です。"
echo "以下の情報を準備してください："
echo ""
echo "1. GitHubユーザー名"
echo "2. Anthropic API Key (既に.envに設定されている場合は不要)"
echo ""
echo "準備ができたら、以下のコマンドを実行してください："
echo ""
echo "node github-auto-setup-chrome.js"
echo ""
echo "または、Chrome自動ログインをテストしたい場合："
echo ""
echo "node test-chrome-login.js"
echo ""
echo "✅ 実行すると以下が自動化されます："
echo "- GitHubにChrome保存パスワードでログイン"
echo "- リポジトリの作成"
echo "- GitHub Secretsの設定"
echo "- コードのプッシュ"
echo "- GitHub Actionsの起動"
echo ""
echo "🌐 ブラウザウィンドウが開きます。"
echo "Chromeにパスワードが保存されていれば、自動でログインします。"